spring:
  application:
    name: DepartmentService
    
server:
  port: 8093
  
logging:
  level:
    com.charan.* : DEBUG
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8020/eureka
    register-with-eureka: true
    fetchRegistry: true
  instance:
    prefer-ip-address: true
    